Repository codekittyshow/code-kitty-api, pull requests merged in 2021-09, with the labels that each got.

#4 Category CRUD implementation
  .gitignore
  src/api/category/category.class.ts
  src/api/category/category.controller.ts
  src/api/category/category.interface.ts
  src/api/category/category.route.ts
  src/api/index.ts
  tsconfig.json
Labels: backend, winner :trophy:

#9 Automatic Labeling
  .github/workflows/label-bot.yml
Labels: approved

#10 Post Endpoint Done
  src/api/index.ts
  src/api/post/post.class.ts
  src/api/post/post.controller.ts
  src/api/post/post.interface.ts
  src/api/post/post.route.ts
  src/config/config.ts
Labels: winner :trophy:
